image: node:11.10
stages:
  - deploy

cache:
  key: global-cache
  paths:
    - node_modules/
  policy: pull-push

pages:
  stage: deploy
  script:
    - npm install
    - CI=true npm run build # setting CI will treat build warnings as failures and run in non-watch mode
    # Gitlab pages requires the directory with static content to be called public
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
