image: node:11.10
stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm run build
    # Gitlab pages requires the directory with static content to be called public
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  # only:
  #   - master
